"""Added PNG image field

Revision ID: d605ed87e91f
Revises: e545dfa2eaf3
Create Date: 2025-03-21 19:08:25.463963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd605ed87e91f'
down_revision = 'e545dfa2eaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_png', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('image_url_png')

    # ### end Alembic commands ###
